export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  DASHBOARD_DIRECTOR: '/dashboard/director',
  CLIENTS: '/clients',
  CLIENT_DETAIL: (id: number | string) => `/clients/${id}`,
  LEADS: '/leads',
  BOOKINGS_SCHEDULE: '/bookings/schedule',
  BOOKINGS: '/bookings',
  MEMBERSHIPS: '/memberships',
  MEMBERSHIPS_ISSUE: '/memberships/issue',
  FINANCE: '/finance',
  QR_SCANNER: '/qr-scanner',
  MANAGE_COURTS: '/manage/courts',
  MANAGE_SERVICES: '/manage/services',
  MANAGE_MARKETING: '/manage/marketing',
  MANAGE_NEWS: '/manage/news',
  MANAGE_MEMBERSHIPS: '/manage/memberships',
  MANAGE_SETTINGS: '/manage/settings',
  TOURNAMENTS: '/tournaments',
  TOURNAMENT_DETAIL: (id: number | string) => `/tournaments/${id}`,
  MANAGE_STAFF: '/manage/staff',
  PROFILE: '/profile',
} as const
